[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/recipe"
  to = "/.netlify/functions/recipe"
  status = 200

[[redirects]]
  from = "/api/restaurants"
  to = "/.netlify/functions/restaurants"
  status = 200

